const host = {
  NEXT_PUBLIC_SPOTIFY_CLIENT_ID: process.env.NEXT_PUBLIC_SPOTIFY_CLIENT_ID,
  NEXT_PUBLIC_SPOTIFY_CLIENT_SECRET:
    process.env.NEXT_PUBLIC_SPOTIFY_CLIENT_SECRET,
  NEXT_PUBLIC_SPOTIFY_REDIRECT_URI:
    process.env.NEXT_PUBLIC_SPOTIFY_REDIRECT_URI,
  NEXT_PUBLIC_LASTFM_API_KEY: process.env.NEXT_PUBLIC_LASTFM_API_KEY,
  NEXT_PUBLIC_LASTFM_SHARED_SECRET:
    process.env.NEXT_PUBLIC_LASTFM_SHARED_SECRET,
  NEXT_PUBLIC_LASTFM_REDIRECT_URI: process.env.NEXT_PUBLIC_LASTFM_REDIRECT_URI,
  NEXT_PUBLIC_LASTFM_USERNAME: process.env.NEXT_PUBLIC_LASTFM_USERNAME,
};

export default host;
